# Generated by mac/homebrew/cask.sh — edit that, not this.
cask "prompto-native" do
  version "0.2.3"
  sha256 "c25a01de998513ff73951102ed7f4593e51852f372b1e3e432442d7c79d7330f"

  # The same immutable per-version zip the in-app updater downloads, from the
  # same blob store latest.json points at. verified: is what tells brew audit
  # that a download host different from the homepage is deliberate.
  url "https://gykjgshesgw30zkd.public.blob.vercel-storage.com/downloads/Prompto-Native-#{version}-mac-arm64.zip",
      verified: "gykjgshesgw30zkd.public.blob.vercel-storage.com/"
  name "Prompto Native"
  desc "Keyboard deck that pastes saved prompts into any app"
  homepage "https://promptdeck-wheat.vercel.app/"

  livecheck do
    url "https://gykjgshesgw30zkd.public.blob.vercel-storage.com/downloads/latest.json"
    strategy :json do |json|
      json["version"]
    end
  end

  # Not a description of the app being self-updating — an instruction to brew to
  # keep its hands off. `brew upgrade --cask` uninstalls before it reinstalls,
  # and macOS prunes an app's privacy grants the moment its bundle stops
  # existing. That would cost the Accessibility permission this app needs to
  # paste, which is the one thing it exists to do, and is exactly why the app's
  # own updater dittos over the bundle in place instead. So brew installs the
  # first copy and Update.swift carries it from there.
  auto_updates true
  # build.sh is one swiftc call on the host, so the binary is thin arm64.
  depends_on arch: :arm64
  # LSMinimumSystemVersion, as a floor and not an exact match — the bare symbol
  # is what the string form ">= :ventura" was deprecated in favour of.
  depends_on macos: :ventura

  app "Prompto Native.app"

  # Signed with an Apple Development certificate, which is not a distribution
  # identity: Gatekeeper rejects a quarantined build carrying one outright, and
  # brew quarantines every cask artefact by default. Dropping the attribute is
  # what `--no-quarantine` does, done here so nobody has to know to pass it.
  # The signature is still checked on launch — and by the updater, which only
  # installs builds satisfying the running copy's designated requirement.
  # The real fix is a Developer ID certificate and notarisation; until then this
  # is the difference between an app that opens and one that says it's damaged.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Prompto Native.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Application Support/Prompto Native",
    "~/Library/Preferences/com.prompto.native.plist",
    "~/Library/Saved Application State/com.prompto.native.savedState",
  ]

  caveats <<~EOS
    Prompto Native needs Accessibility to paste into other apps. Grant it once in
    System Settings › Privacy & Security › Accessibility; the permission is keyed
    to the signature, so later versions keep it.

    Updates install themselves — the app swaps its own bundle in place to hold on
    to that grant. Don't run `brew upgrade --cask --greedy` over it, which would
    delete the bundle and take the permission with it.

    This build is signed but not notarised, so the installer strips the quarantine
    attribute for you.
  EOS
end
